# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/voja/psdsProject/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/voja/psdsProject/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths {
  c:/Users/voja/psdsProject/ip_repo/AXI_UART_Lite_1.0
  c:/Users/voja/psdsProject/ip_repo/simpleMultiplier_1.0
  c:/Users/voja/psdsProject/project_1
} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/voja/psdsProject/project_1/project_1.srcs/sources_1/new/TX_control.vhd
  C:/Users/voja/psdsProject/project_1/project_1.srcs/sources_1/new/STD_FIFO.vhd
  C:/Users/voja/psdsProject/project_1/project_1.srcs/sources_1/new/simp_reg.vhd
  C:/Users/voja/psdsProject/project_1/project_1.srcs/sources_1/new/RX_control.vhd
  C:/Users/voja/psdsProject/project_1/project_1.srcs/sources_1/new/rising_edge_detect.vhd
  C:/Users/voja/psdsProject/project_1/project_1.srcs/sources_1/new/Boud_rate_gen.vhd
  C:/Users/voja/psdsProject/project_1/project_1.srcs/sources_1/new/Int_control.vhd
  C:/Users/voja/psdsProject/project_1/project_1.srcs/sources_1/new/AXI_UART_Lite_v1_0_S00_AXI.vhd
  C:/Users/voja/psdsProject/project_1/project_1.srcs/sources_1/new/top_level.vhd
  C:/Users/voja/psdsProject/project_1/project_1.srcs/sources_1/new/AXI_UART_Lite_v1_0.vhd
}
synth_design -top AXI_UART_Lite_v1_0 -part xc7z020clg484-1
write_checkpoint -noxdef AXI_UART_Lite_v1_0.dcp
catch { report_utilization -file AXI_UART_Lite_v1_0_utilization_synth.rpt -pb AXI_UART_Lite_v1_0_utilization_synth.pb }
